### PR TITLE
Logout2

### PR DESCRIPTION
**Pull request by BenNewman90**
- Clicking the home button removes the jwt from local storage
- Clicking the home button makes a fetch request to the new logout end point and ends the express-session session.

### CODE REVIEW

**Comment by sunuwars** [comment]
I am a little unsure as I think the good way to word this issue is:
Clicking the **logout** button removes the jwt from local storage
Clicking the **logout** button makes a fetch request to the new logout end point and ends the express-session session.
and with this wording it would imply a separate logoutButton component with signed-in pages (instead of home btn)   
and homeButton would render if it is local government page

**Comment by BenNewman90** [comment]
> I am a little unsure as I think the good way to word this issue is:
> Clicking the **logout** button removes the jwt from local storage
> Clicking the **logout** button makes a fetch request to the new logout end point and ends the express-session session.
> and with this wording it would imply a separate logoutButton component with signed-in pages (instead of home btn)
> and homeButton would render if it is local government page

I called it the 'home' button, because the icon has not yet been changed to the logout button. It is called the home button in the components. They will be the same component, but will use a different img src depending on which url is open

**Comment by sunuwars** [comment]
I called it the 'home' button, because the icon has not yet been changed to the logout button. It is called the home button in the components. **They will be the same component,** but will use a different img src depending on which url is open
I am confused in this part **they will be the same component**

**Comment by BenNewman90** [comment]
> I called it the 'home' button, because the icon has not yet been changed to the logout button. It is called the home button in the components. **They will be the same component,** but will use a different img src depending on which url is open

You can make the component render differently, by passing in different props

**Comment by sunuwars** [comment]
but do we not want to make a dedicated component for sth as important as logout?

**Comment by BenNewman90** [comment]
> but do we not want to make a dedicated component for sth as important as logout?

I see no reason why. It does exactly the same thing. It basically is a dedicated component. The image just changes to a home when someone in the local council is logged in. To me, that just sounds like extra work for no benefit.

**Comment by BenNewman90** [comment]
> > but do we not want to make a dedicated component for sth as important as logout?
> 
> I see no reason why. It does exactly the same thing. It basically is a dedicated component. The image just changes to a home when someone in the local council is logged in. To me, that just sounds like extra work for no benefit.

**Comment by sunuwars** [comment]
ok sorry for stretching this conversation long ...
I think **logout** means making api request and revoking any authorised tokens.
while **home** means for someone who is not logged in(like local government page) , who then are navigated to home page and given opportunity to login or signup...
so these two are very different functionalities

**Comment by BenNewman90** [comment]
> while **home** means for someone who is not logged in(like local government page) , who then are navigated to home page and given opportunity to login or signup...

For the user, they will appear like two separate buttons

**Pull request merged**
